import {
  Github,
  Twitter,
  Linkedin,
  Mail,
  ArrowRight,
  CheckCircle2,
  ChevronRight,
  ChevronLeft,
  Menu,
  X,
  Loader2,
  Search,
  Settings,
  User,
  LogOut,
  Plus,
  Trash2,
  Edit,
  Copy,
  Share2,
  Download,
  Upload,
  File,
  Folder,
  Mic,
  MicOff,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Clock,
  Calendar,
  Bell,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  Check,
  XCircle,
  ChevronDown,
  ChevronUp,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  Menu as MenuIcon,
  X as XIcon,
  Loader2 as Loader2Icon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  User as UserIcon,
  LogOut as LogOutIcon,
  Plus as PlusIcon,
  Trash2 as Trash2Icon,
  Edit as EditIcon,
  Copy as CopyIcon,
  Share2 as Share2Icon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  File as FileIcon,
  Folder as FolderIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  Bell as BellIcon,
  HelpCircle as HelpCircleIcon,
  Info as InfoIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  Check as CheckIcon,
  XCircle as XCircleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
} from "lucide-react";

// Импортируем React-компоненты иконок
import Logo from "./logo";
import LogoDark from "./logo-dark";
import Soc2 from "./soc2";
import Hipaa from "./hipaa";
import Gdpr from "./gdpr";
import Soc2Dark from "./soc2-dark";
import HipaaDark from "./hipaa-dark";
import GdprDark from "./gdpr-dark";

export const Icons = {
  // Lucide иконки
  github: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  mail: Mail,
  arrowRight: ArrowRight,
  checkCircle: CheckCircle2,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  x: X,
  loader: Loader2,
  search: Search,
  settings: Settings,
  user: User,
  logOut: LogOut,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  copy: Copy,
  share: Share2,
  download: Download,
  upload: Upload,
  file: File,
  folder: Folder,
  mic: Mic,
  micOff: MicOff,
  play: Play,
  pause: Pause,
  volume: Volume2,
  volumeOff: VolumeX,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  help: HelpCircle,
  info: Info,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  check: Check,
  xCircle: XCircle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRightIcon: ChevronRightIcon,
  chevronLeftIcon: ChevronLeftIcon,
  menuIcon: MenuIcon,
  xIcon: XIcon,
  loaderIcon: Loader2Icon,
  searchIcon: SearchIcon,
  settingsIcon: SettingsIcon,
  userIcon: UserIcon,
  logOutIcon: LogOutIcon,
  plusIcon: PlusIcon,
  trashIcon: Trash2Icon,
  editIcon: EditIcon,
  copyIcon: CopyIcon,
  shareIcon: Share2Icon,
  downloadIcon: DownloadIcon,
  uploadIcon: UploadIcon,
  fileIcon: FileIcon,
  folderIcon: FolderIcon,
  micIcon: MicIcon,
  micOffIcon: MicOffIcon,
  playIcon: PlayIcon,
  pauseIcon: PauseIcon,
  volumeIcon: Volume2Icon,
  volumeOffIcon: VolumeXIcon,
  clockIcon: ClockIcon,
  calendarIcon: CalendarIcon,
  bellIcon: BellIcon,
  helpIcon: HelpCircleIcon,
  infoIcon: InfoIcon,
  alertCircleIcon: AlertCircleIcon,
  alertTriangleIcon: AlertTriangleIcon,
  checkIcon: CheckIcon,
  xCircleIcon: XCircleIcon,
  chevronDownIcon: ChevronDownIcon,
  chevronUpIcon: ChevronUpIcon,

  // SVG иконки
  logo: Logo,
  logoDark: LogoDark,
  soc2: Soc2,
  hipaa: Hipaa,
  gdpr: Gdpr,
  soc2Dark: Soc2Dark,
  hipaaDark: HipaaDark,
  gdprDark: GdprDark,
};
